### ISSUE TITLE
Why does master not send slave status requests?

### ISSUE THREAD

**Issue by raintonr** [raintonr/hormann-hcp#1]
The master does perform bus scan, and after replying to this, would have thought it would then move on to issue status requests for slaves that responded to it's scan. But this doesn't happen.

**Comment by raintonr** [comment]
I wonder if @Bouni can help? ;)

**Comment by Bouni** [comment]
Let me lookup my old notes I took when I was actively reverse engineer this.
I'll post what I got soon...

**Comment by raintonr** [comment]
Thanks. To explain some context further... I have a LineaMatic P sliding gate motor and a USB RS485 adapter connected to Linux PC.

The code in this repo works insomuch as it correctly decodes messages received from the LineaMatic. This way one can see if the motor is fully open, fully closed, moving, etc. This information comes from master broadcast messages.

As you know, this device also sends out bus scan messages. They are interleaved with the broadcasts. Ie. one bus scan, one broadcast, one bus scan, one broadcast, etc.

When the code in this repo receives a bus scan targeting at it's address (I used `0x28` copied from your UAP1) it replies. Here's some logging from couple of these and some broadcast status messages when I manually pressed the motor button:

```
+12	Slave query	 28820180
+1	Sending 5	 80921428ac
Drain emitted

+11	Slave query	 28020180
+0	Sending 5	 80121428a7
Drain emitted

+61	New status	 00526006 -> 1100000

+61	New status	 00720006 -> 0

+11	Slave query	 28820180
+0	Sending 5	 80921428ac
Drain emitted
```

After replying (eg. `80921428ac`) I would expect further queries of the Slave Status Request, but none appear. Maybe the motor isn't correctly receiving the bus scan reply?

**Comment by Bouni** [comment]
A while ago someone contacted me and told me he was able to decode the broadcast status as well as trigger a gate open.
His message was in german but I'll try to translate it as good as possible:

```
...
It works, I can emulate a UAP1 and remote control my gate.

Py plan was to control the gate over Home-Assistant (Hass.io) without relying on a UAP1.
My setup is: Supramatic <- RS485 -> PIC24 <- UART -> ESP8266 <- WIFI -> Raspberry (Hass.io)

The timing constraints on the RS485 bus are quite strict and the ESP8266 is not able to send a syncbreak, thats why I put the PIC24 in between.

You did a mistake when you analyzed the telegrams.
The correct decoding of the broadcast status is:

Example: 0x00 0x52 0x01 0x02 0xD0 => Gate completely open
0x00 : Broadcast
0x52 : ((0x52 & 0xF0) >> 4) = 5 = Counter, (0x12 & 0x0F) = 2 = Length
0x01 : Statusbyte 1
  Bit 0x01 = Gate open
  Bit 0x02 = Gate closed 
  Bit 0x04 = Option relay (presumably)
  Bit 0x08 = Light relay (presumably) On my device the bits 0x04 and 0x08 are simultaneously on/off
  Bit 0x10 = Error pending
  Bit 0x20 = Direction (0x20 = Closing, 0x00 Opening)
  Bit 0x40 = Gate closes
  Bit 0x80 = Gate in ventilation position
0x02 : Statusbyte 2
  Bit 0x01 = ? - always 0 for me
  Bit 0x02 = ? - always 1 for me
  Bit 0x04 = ? - always 0 for me (was 1 only one time for me)
  Bit 0x08 = ? - always 0 for me
  Bit 0x10 = ? - always 0 for me
  Bit 0x20 = ? - always 0 for me
  Bit 0x40 = ? - always 0 for me
  Bit 0x80 = ? - always 0 for me
0xD0 : CRC as described by you

Out of the  "Slave status response" I've identified the following:
Example: 0x80 0x63 0x29 0x01 0x10 0x4B => Trigger Gate open
0x80 : Target = Master
0x63 : ((0x63 & 0xF0) >> 4) = 6 = Counter, (0x12 & 0x0F) = 3 = Length
0x29 : Always 0x29 = Status Response
0x01 : Control byte 1
  Bit 0x01 = Trigger Gate open
  Bit 0x02 = Trigger Gate close
  Bit 0x04 = Trigger reverse ??? (not sure about that)
  Bit 0x08 = Toggle light relay
  Bit 0x10 = Trigger ventilation position
  Bit 0x20 = ? - no idea
  Bit 0x40 = ? - no idea
  Bit 0x80 = ? - no idea
0x10 : Control byte 2
  Bit 0x01 = ? - no idea
  Bit 0x02 = ? - no idea
  Bit 0x04 = ? - no idea
  Bit 0x08 = ? - no idea
  Bit 0x10 = Clearance trough UAP1 (Is the gate moving and this bit is set to 0, the gate stops and the motor shows error 4)
  Bit 0x20 = ? - no idea
  Bit 0x40 = ? - no idea
  Bit 0x80 = ? - no idea
0x4B : CRC as described by you
```

He also provided source code, but I'll first ask for permission before I post it.

**Comment by raintonr** [comment]
Thank you. That sounds very promising.

When he says, `The timing constraints on the RS485 bus are quite strict and the ESP8266 is not able to send a syncbreak, thats why I put the PIC24 in between.` I don't understand this... so perhaps there is the problem! ;)

I do see how in response to the slave status he managed to trigger actions (`Example: 0x80 0x63 0x29 0x01 0x10 0x4B => Trigger Gate open`) but as I'm not seeing any slave status message to actually respond to... again, there's an issue.

I think the transmit logic in my code is not correct. When responding to the master, does one have to start with some zero padding (I did try this, but no difference), send the message at a very specific time interval, or some other precise way to actually have the master process the response?

**Comment by Bouni** [comment]
As far as I remember the sync break is a period at the start (or the end?) of a frame. Usually they have a specific length, but Hörmann uses a longer period and therefore a "normal" UART cannot automatically do that.
I suggested nback then that we might get this to work using a soft serial where you are completely free in timing.

I'll look through the code and see if I can figure out what the key to the problem is later today.

**Comment by raintonr** [comment]
Last night I modified the code to use `nanotimer` and wait a very specific amount of time before replying to bus scan. I put this in a loop and added 10us each time. Left it running for hours but none of the replies ever seem to have been successful. *I am measuring success by the fact that a slave status request never followed - indicating the master hasn't realised that slave exists.

I looked in the patent and see there is mention of `ACK` messages. Tried adding one but no success.

I also see in the patent if a device with higher address than the motor (address `0x80`) appears on the bus, it can take over and become master, the motor then is supposed to become a slave. I may try and play with that later.

**Comment by raintonr** [comment]
> I suggested nback then that we might get this to work using a soft serial where you are completely free in timing.

Yes, having done many timing experiments on my PC I am beginning to think you are correct.

Is it possible you can attach the raw logic analysis file with 'conversation' between your door and UAP1 here? So I can look at the exact timing.

I have a few spare Arduinos here, but no MAX485 converter (doh!) so will get one of those to do some soft serial experiments.

**Comment by stephan192** [comment]
Hi, i'm the one Bouni mentioned.

Every message on the bus must start with a sync break (according to the LIN standard). A sync break are at least 13bits low, this is not the same as sending one or two zeros (each of them is only 8bits low). As the name says a sync break breaks the "normal" protocol frame to trigger an error = resync in every connected device.
I haven't seen USB dongles that can send sync breaks. I only have seen this feature in microcontrollers.

The second point is:
After you have received a message you have just a small time window in which you must start answering. According to my measurements you must start 3-10ms after the last received byte with the sync break of your message.

**Comment by raintonr** [comment]
Thank you @stephan192, this is super useful info.

It is key to know that the break must be sent before any message, and it must be 13 low bits. Ie. we have to hold the serial line high for at least as long as 13 bits takes to transmit at 19200baud.

In fact, this can be achieved by setting the baud rate down to 9600, data bits to 7 then sending a zero, which in effect holds the transmit line high for long enough. Remembering to turn communications parameters back to normal before continuing.

I tried this and now it is working. It was able to send a correct reply to the bus scan and the LineaMatic began sending slave status request messages. Success!

Thank you for all your help :)
