### ISSUE TITLE
Clear protocol description

### ISSUE THREAD

**Issue by Bouni** [raintonr/hormann-hcp#4]
Do you think we can describe the protocoll in either the README.md or a sepearte .md file to an extend that allows to easily understand the protocoll?

Ideally with timing graphics and detailed explanations of the pitfalls like the sync break and how to overcome them.

I'll help you with that obviously!

**Comment by raintonr** [comment]
Absolutely. If you want to write stuff in the readme and make a PR, that would be great :)

**Comment by Bouni** [comment]
Nice, I'll do it as I find some spare time!

**Comment by Bouni** [comment]
@stephan192 did the work already in his repo: https://github.com/stephan192/hoermann_door/blob/main/docs/hoermann.md
