### ISSUE TITLE
Timing with baud rate trick

### ISSUE THREAD

**Issue by Bouni** [raintonr/hormann-hcp#5]
@raintonr Do you have access to a logic analyzer or an oscilloscope? 
I'm really interested how the signal looks when you send something using your baud rate switching trick!
If you coud provide a trace / picture that would be awesome!

**Comment by raintonr** [comment]
Sadly not :(

Do you have any device there you can run similar code on?

**Comment by Bouni** [comment]
Maybe, I will see if I can run your code on lets say a RPi and if I find a USB Rs485 dongle to use.

**Comment by raintonr** [comment]
TBH, any serial interface should do. If you have an RPi, you could try it on the built in UART easily enough, right?

**Comment by Bouni** [comment]
Yes, I'm just not sure if I have RPi laying around that is not part of a running system.
Maybe I will do a test with an ESP32 + Max485 and see if that will work out as well (Sure, not with your nodejs code ;-))

**Comment by riogrande75** [comment]
I wanna take part and will try this code on a arm based orange pi zero connected with a usb-rs485 adapter to my Supramatic E2.
I have oscilloscope and logic analyzer but unfortunately my garage is very wet and cold these days :-(
Also my car is just underneath the door opener so I have to use a pretty long cable.
Hopefully I can post some results soon.

**Comment by raintonr** [comment]
> I wanna take part and will try this code on a arm based orange pi zero connected with a usb-rs485 adapter to my Supramatic E2.

Excellent. Thanks for your help.

FWIW, this code is only experimental, but works fine here. Once running, you basically flip the command bits for the motor (open, close, etc) with keyboard 1, 2, 3...8 (8 bits).

Would be pleased to hear how you get on. Any probs, feel free to open a new ticket.

**Comment by Bouni** [comment]
I found the old traces I took back in 2018. I attached them to my [blog post](https://blog.bouni.de/2018/reverse-engeneering-the-hormann-uap1-protocoll.html).
The recording was done on the UART side of the UAP1, meaning that you see the same bits on RX and TX when the UAP1 is sending.

![UAP1-1](https://user-images.githubusercontent.com/948965/108702835-148f7200-750a-11eb-8273-3e9f3e833d86.jpg)

![UAP1-2](https://user-images.githubusercontent.com/948965/108702858-1ce7ad00-750a-11eb-8056-b6f637387128.jpg)

I measured the length of the syncbreak at multiple spots and it is between 0.92 and 0.93ms in length.

![Syncbreak](https://user-images.githubusercontent.com/948965/108702883-240ebb00-750a-11eb-971c-6c660f78b7c6.jpg)

![Syncbreak-2](https://user-images.githubusercontent.com/948965/108702886-2709ab80-750a-11eb-9e19-7fee32e7900b.jpg)

A bit is 50us long

![Bit](https://user-images.githubusercontent.com/948965/108703116-79e36300-750a-11eb-9737-4ce687df744b.jpg)

According to the internet, at 19200 baud the length of a bit is 52.083333333333us, so that seems correct then.

But that means on the other hand that the syncbreak is 0.92ms / 0.05ms = 18.4 bits long. I guess that it should be just longer than 13 bits.

I also did a quick test with an ESP32 where I switched the mode of an output pin between Serial TX and GPIO output pin to generate a syncbreak an that works just fine. So I guess we're close to have an ESP32 + MAX3485 interfacing with our gates.

**Comment by Bouni** [comment]
Quick update:

This is done using the ESP32 with syncbreak by GPIO:

![image](https://user-images.githubusercontent.com/948965/108708527-d8f8a600-7511-11eb-9024-8dcb88c6f734.png)

I took the byte values from one of the obove screenshots as example values just for comparison.

**Comment by raintonr** [comment]
Looks perfect. Thx.

**Comment by ljames8** [comment]
Hi, I just stumbled upon this issue.
I am working on a HCP typescript client, and I saw how you solved this sync break challenge, nice.
It seems there now is a supported way to send a break signal using node serialport package: https://serialport.io/docs/api-stream#set.
`serialport` doc is quite obscure, I spent some time before finding this.

I tried it, you can set the `BRK` flag to `true` for the appropriate duration and then back to `false` , it seems to work well.
