### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Bouni** [raintonr/hormann-hcp#7]
I strugle a bit to understand how to use the tool.

When I start it with `nodejs hormann-hcp.js`, I get some output:

```
Setting up port...
Initiating parser...
Opening port...
```

When I then press a number key (1 up to 8) I can set the according bit for the response to the master (the drive) which is stored in `ourStatus`

```
Sending command 4
OurStatus: 1000
Sending command 2
OurStatus: 1010
Sending command 2
OurStatus: 1000
```

Is it even possible to send an answer with multiple bits set at a time?
Your comment in the code says:

```
// Command mask for LineaMatic P:
// +------- (0x80) Unknown
//  +------ (0x40) Unknown
//   +----- (0x20) Unknown
//    +---- (0x10) Moves to 'H' (whatever that means)
//     +--- (0x08) Unknown
//      +-- (0x04) Impulse toggle
//       +- (0x02) Impulse close
//        + (0x01) Impulse open
```

So I guess replying with Impulse close and impulse open at the same time does not work, right?
Wouldn't it make more sense to clear `ourStatus` before setting the bit tha is requested by key press?

**Comment by raintonr** [comment]
> When I then press a number key (1 up to 8) I can set the according bit for the response to the master (the drive) which is stored in `ourStatus`

It's only stored until the next master status request. Then the command is sent and all bits (aside from the error bit) cleared.

I found that if you leave the bits set it appears to have the same effect as mashing that command button and the motor doesn't like it. Ie. it's like hitting the 'open' button on your remote or unit very fast which would cause the door to move/stop/move/stop very fast.

> Is it even possible to send an answer with multiple bits set at a time?

Not right now... well, unless you hit press two keys very fast! ;)

> So I guess replying with Impulse close and impulse open at the same time does not work, right?

I didn't try, but that sounds illogical.

> Wouldn't it make more sense to clear `ourStatus` before setting the bit tha is requested by key press?

In fact, that is exactly what happens (see point above above clearing bits once command is sent).
