### ISSUE TITLE
Feature request: output of door status

### ISSUE THREAD

**Issue by riogrande75** [raintonr/hormann-hcp#8]
According to Bouni's protocol findings it should be possible to have the status of a door signalled. This is in fact the main reason I am so interrested in this project. Open/close the door can be done with I/O of a ESP easily but not receiving the actual status.

So can you pls. add a output to see the actual status of the door (open/closed) and maybe other infos (lightning,..) too?

**Comment by raintonr** [comment]
In fact, this already happens. When the status changes, that new status is output. It isn't printed on every status packet received as it would just flood the output.

Don't forget this is only experimental code. I intend to create an ioBroker adapter using the principles here which would therefore have status objects and buttons for sending commands.
